import { describe, expect, it, vi } from "vitest";
import { firstRank, isValidRank, rankAfter, rankBetween } from "./rank";

describe("firstRank", () => {
  it("returns a non-empty string", () => {
    expect(firstRank().length).toBeGreaterThan(0);
  });

  it("is the same as rankBetween(null, null)", () => {
    expect(firstRank()).toBe(rankBetween(null, null));
  });
});

describe("rankAfter", () => {
  it("sorts after the given rank", () => {
    const a = firstRank();
    const b = rankAfter(a);
    expect(b > a).toBe(true);
  });

  it("is the same as rankBetween(rank, null)", () => {
    const a = firstRank();
    expect(rankAfter(a)).toBe(rankBetween(a, null));
  });
});

describe("rankBetween", () => {
  it("sorts strictly between two existing ranks", () => {
    const a = firstRank();
    const c = rankAfter(a);
    const b = rankBetween(a, c);
    expect(a < b).toBe(true);
    expect(b < c).toBe(true);
  });

  it("with a null lower bound sorts before the upper bound", () => {
    const upper = firstRank();
    const r = rankBetween(null, upper);
    expect(r < upper).toBe(true);
  });

  it("warns when a generated rank exceeds the length threshold", () => {
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});

    // Repeatedly inserting directly below the same fixed upper bound is
    // fractional indexing's known worst case — each new key must fit
    // strictly between the last one and `upper`, forcing steady growth.
    const upper = rankAfter(firstRank());
    let lower = firstRank();
    for (let i = 0; i < 250; i++) {
      lower = rankBetween(lower, upper);
    }

    expect(lower.length).toBeGreaterThan(40);
    expect(warnSpy).toHaveBeenCalled();
    expect(warnSpy.mock.calls.some((call) => String(call[0]).includes("exceeds"))).toBe(true);

    warnSpy.mockRestore();
  });
});

describe("isValidRank", () => {
  it("accepts ranks generated by firstRank/rankAfter/rankBetween", () => {
    const a = firstRank();
    const b = rankAfter(a);
    const c = rankBetween(a, b);
    expect(isValidRank(a)).toBe(true);
    expect(isValidRank(b)).toBe(true);
    expect(isValidRank(c)).toBe(true);
  });

  it("rejects a rank with an invalid head character", () => {
    // Only the leading (head/magnitude) character is strictly validated —
    // a digit or punctuation there is what actually crashes a later
    // rankAfter/rankBetween call against a stored bad rank.
    expect(isValidRank("1invalid")).toBe(false);
    expect(isValidRank("#invalid")).toBe(false);
    expect(isValidRank("z")).toBe(false);
  });

  it("rejects an empty string", () => {
    expect(isValidRank("")).toBe(false);
  });
});
